### ISSUE TITLE
The comparison function doesn't work

### ISSUE THREAD

**Issue by ZDProject** [bomsy/brackets-compare#25]
![screen shot 2016-05-03 at 2 47 04 pm](https://cloud.githubusercontent.com/assets/11206745/14976408/0f474f28-113e-11e6-9bf5-256f54e6eb33.png)

There's not any highlights and comments concerning the difference between two HTML files. 

Is this some kind of bug or just that I use it the wrong way?

**Comment by bomsy** [comment]
There might be some conflicts with another extension. try to disable the others and see.

**Comment by tallchap67** [comment]
I have the same issue.  You click the icon and the new pane appears empty.  I have disabled all other extensions and the issue remains.

**Comment by davehallowell** [comment]
Yes. I have the exact same problem. Too bad. I don't see any other extension that can be used to compare.

**Comment by crezaii** [comment]
Same issue. Doesn't highlight even with all other extensions disabled.

**Comment by npoku** [comment]
confirming +1

**Comment by bomsy** [comment]
Looking into this. what versions of brackets are you guys using?

**Comment by crezaii** [comment]
I'm using the latest version: 1.6.

**Comment by davehallowell** [comment]
I am using Release 1.6 build 1.6.0-16680.

**Comment by xuefengwork** [comment]
same issue on version1.6

**Comment by ZDProject** [comment]
Release 1.6 build 1.6.0-16680 (release 3df0ac6fa) 
Thanks for taking care of this. Let me know if I should provide additional information.

**Comment by ngrisouard** [comment]
Same here, same release as ZDProject. Tried with all other extensions disabled as well, but it won't work.

**Comment by dterrazas** [comment]
I had the same issue...nothing changed when I clicked compare.  I disable the only other extension I had installed (Extract for Brackets) and now when I click the compare button it opens in a full white screen where I can see a little bit of code but completely unusable.

![capture](https://cloud.githubusercontent.com/assets/5932271/16194760/3ebfbc44-36c4-11e6-87a3-71dbc3c9fcba.JPG)

**Comment by J3QQ4** [comment]
Same issue. Clicking the compare button doesn't do anything. Disabled all other extensions, didn't help too. 

Here is the error in the javascript console that is logged when I click the Compare button: 

`/thirdparty/CodeMirror/lib/codemirror.js:187 Uncaught TypeError: Cannot read property 'first' of null
Display @ /thirdparty/CodeMirror/lib/codemirror.js:187
CodeMirror @ /thirdparty/CodeMirror/lib/codemirror.js:74
CodeMirror @ /thirdparty/CodeMirror/lib/codemirror.js:62
CodeMirror.MergeView @ cm_merge.js:471
CodeMirror.MergeView @ cm_merge.js:439
(anonymous function) @ main.js:116
switchCompareMode @ main.js:56
(anonymous function) @ main.js:111
n.event.dispatch @ thirdparty.min.js:20
r.handle @ thirdparty.min.js:20`

**Comment by bradanlane** [comment]
a further clarification on what 

> "you select the directory where the files are located. Users need to click "Open Folder" in the left pane of Brackets, and select the files to compare from that folder only."

The does not work on files in subfolders of the selected folder. As @J3QQ4 describes, you must first "Open folder ..." and select the folder that directly has the files to compare.

This makes is good for single files but not for projects. Even with single files, it would be helpful to be able to compare files from different directories. (not being an 'extensions developer', I am not sure how difficult this will be)

**Comment by bomsy** [comment]
hey guys, I've released v 0.2.5. Please update and see if issues are fix.

**Comment by bomsy** [comment]
latest version is 0.2.6, Should fix all issues.

**Comment by SkellyCT** [comment]
Well I'm now on 0.2.7 and it still doesn't work unfortunately.

**Comment by bomsy** [comment]
what issue are you getting?

**Comment by SkellyCT** [comment]
It simply doesn't do anything. Doesn't compare. I have updated to all the latest versions.  
I have two documents open but when I click on the compare icon nothing happens. I used existing long ones and tried new short ones to test. Nothing.

**Comment by J3QQ4** [comment]
@SkellyCT you should press F12 to see if there are any error in the javascript console.

**Comment by bomsy** [comment]
@SkellyCT Ur probably getting a specific issue. pls could you press F12 as mention by @J3QQ4, and let me know so i can fix it up for you. thanks!!

**Comment by webs05** [comment]
Just in case it helps someone else in the future, I had to save the files first before the comparison plugin worked. IE, you can't just copy paste stuff into an unsaved file and click diff icon.
